#:kivy 2.3.0

<Gerenciador>:
    Menu:
        name: 'menu'
    Tarefas:

<Menu>:
    BoxLayout:
        orientation: 'vertical'
        padding: [20, 40]  # Mantém o menu centralizado, adaptado a diferentes tamanhos de tela
        spacing: 20
        BoxLayout:
            size_hint_y: 0.5  # Aumenta a responsividade da imagem
            Image:
                source: 'task_logo.png'
                allow_stretch: True
                keep_ratio: True

        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 0.5
            spacing: 10
            Button:
                text: 'Tarefas'
                size_hint_y: None
                height: 50
                on_release: app.root.current = 'tarefas'
            Button:
                text: 'Assistente'
                size_hint_y: None
                height: 50
            Button:
                text: 'Sair'
                size_hint_y: None
                height: 50
                on_release: app.stop()

<Tarefas>:
    name: 'tarefas'
    BoxLayout:
        orientation: 'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Tarefas'
                    on_release: app.root.current = 'menu'
                ActionButton:
                    text: 'Sair'
                    on_release: app.stop()
        ScrollView:
            BoxLayout:
                id: box
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height

        BoxLayout:
            size_hint_y: None
            height: 60
            TextInput:
                id: texto
                hint_text: 'Nova Tarefa'
            Button:
                text: '+'
                size_hint_x: None
                width: 60
                on_release: root.add_widget_tarefa()

<Tarefa>:
    size_hint_y: None
    height: 60
    BoxLayout:
        Label:
            id: label
            font_size: 30
        Button:
            text: 'X'
            size_hint_x: None
            width: 60
            on_release: app.root.get_screen('tarefas').ids.box.remove_widget(root)
